GET http://localhost:4004/sap/opu/odata/sap/API_SALES_ORDER/OrderSet HTTP/1.1

###
POST  http://localhost:4004/sap/opu/odata/sap/API_SALES_ORDER/OrderSet HTTP/1.1
Content-Type: application/json

{ "orderid": 7001,
      "customername": "Ankush CAPM" ,
      "contactperson": "Ankush",
      "grossamount": 4000,
      "currency": "USD"
}